/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookstoremanagement.frames;

import static bookstoremanagement.MainPage.QuyenTable;
import static bookstoremanagement.MainPage.deleteTable;
import java.awt.Color;
import javax.swing.JPanel;
import java.awt.event.ItemEvent;
import bookstoremanagement.model.Frontend.FormThemSua.ThemSuaQuyenForm;
import static bookstoremanagement.frames.ChonMaQuyenForm.SubQuyenTable;
import bookstoremanagement.model.Backend.Quyen.QuanLyQuyenBUS;
import bookstoremanagement.model.Frontend.FormHienThi.HienThiQuyen;
import javax.swing.JFrame;

/**
 *
 * @author songnguyen
 */
public class addQuyen extends javax.swing.JFrame {
     public static void setText()
    {
        String text = (String) SubQuyenTable.getValueAt(SubQuyenTable.getSelectedRow(), 1);
        
        addTK.txtMaQuyen.setText(text);
    }
    
   
    public void changecolor(JPanel hover, Color rand) {
        hover.setBackground(rand);
    }
    
    
    public static String ChiTietQuyen()
    {   
        String chitietquyen = "";
        
        if(checkboxBH.getState())
        {
            chitietquyen += "qlBanHang";
        }
        if(checkboxNH.getState())
        {
            chitietquyen += "qlNhapHang";
        }
        if(checkboxSP.getState())
        {
            chitietquyen += comboSP.getSelectedIndex() == 0 ? "xemSanPham" : "qlSanPham";
        }
        if(checkboxHD.getState())
        {
            chitietquyen += comboHD.getSelectedIndex() == 0 ? "xemHoaDon" : "qlHoaDon";
        }
        if(checkboxKM.getState())
        {
            chitietquyen += comboKM.getSelectedIndex() == 0 ? "xemKhuyenMai" : "qlKhuyenMai";
        }
        if(checkboxNV.getState())
        {
            chitietquyen += comboNV.getSelectedIndex() == 0 ? "xemNhanVien" : "qlNhanVien";
        }
        if(checkboxKH.getState())
        {
            chitietquyen += comboKH.getSelectedIndex() == 0 ? "xemKhachHang" : "qlKhachHang";
        }
        if(checkboxPN.getState())
        {
            chitietquyen += comboPN.getSelectedIndex() == 0 ? "xemPhieuNhap" : "qlPhieuNhap";
        }
        if(checkboxNCC.getState())
        {
            chitietquyen += comboNCC.getSelectedIndex() == 0 ? "xemNCC" : "qlNCC";
        }
        if(checkboxTK.getState())
        {
            chitietquyen += comboTK.getSelectedIndex() == 0 ? "xemTaiKhoan" : "qlTaiKhoan";
        }
        if(checkboxQuyen.getState())
        {
            chitietquyen += comboQuyen.getSelectedIndex() == 0 ? "xemQuyen" : "qlQuyen";
        }
        
        return chitietquyen;
    }
    /**
     * Creates new form addQuyen
     */
    public addQuyen() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txMaQuyen = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txTenQuyen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BHthem = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        BHhuy = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        checkboxBH = new java.awt.Checkbox();
        checkboxNH = new java.awt.Checkbox();
        comboBH = new javax.swing.JComboBox<>();
        comboNH = new javax.swing.JComboBox<>();
        checkboxSP = new java.awt.Checkbox();
        comboSP = new javax.swing.JComboBox<>();
        checkboxNV = new java.awt.Checkbox();
        comboNCC = new javax.swing.JComboBox<>();
        checkboxNCC = new java.awt.Checkbox();
        comboKH = new javax.swing.JComboBox<>();
        checkboxKH = new java.awt.Checkbox();
        checkboxTK = new java.awt.Checkbox();
        comboTK = new javax.swing.JComboBox<>();
        comboHD = new javax.swing.JComboBox<>();
        checkboxHD = new java.awt.Checkbox();
        checkboxKM = new java.awt.Checkbox();
        comboKM = new javax.swing.JComboBox<>();
        checkboxPN = new java.awt.Checkbox();
        comboPN = new javax.swing.JComboBox<>();
        comboNV = new javax.swing.JComboBox<>();
        checkboxQuyen = new java.awt.Checkbox();
        comboQuyen = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txMaQuyen.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mã quyền");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txMaQuyen)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 104, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txMaQuyen, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txTenQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTenQuyenActionPerformed(evt);
            }
        });
        jPanel3.add(txTenQuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 33));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên quyền");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 83, 30));

        BHthem.setBackground(new java.awt.Color(0, 204, 204));
        BHthem.setPreferredSize(new java.awt.Dimension(80, 24));
        BHthem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BHthemMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BHthemMouseReleased(evt);
            }
        });

        jLabel58.setBackground(new java.awt.Color(255, 255, 255));
        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("Thêm");

        javax.swing.GroupLayout BHthemLayout = new javax.swing.GroupLayout(BHthem);
        BHthem.setLayout(BHthemLayout);
        BHthemLayout.setHorizontalGroup(
            BHthemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BHthemLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        BHthemLayout.setVerticalGroup(
            BHthemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        BHhuy.setBackground(new java.awt.Color(255, 0, 0));
        BHhuy.setPreferredSize(new java.awt.Dimension(80, 24));
        BHhuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BHhuyMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BHhuyMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BHhuyMouseReleased(evt);
            }
        });

        jLabel59.setBackground(new java.awt.Color(255, 255, 255));
        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("Hủy");

        javax.swing.GroupLayout BHhuyLayout = new javax.swing.GroupLayout(BHhuy);
        BHhuy.setLayout(BHhuyLayout);
        BHhuyLayout.setHorizontalGroup(
            BHhuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BHhuyLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        BHhuyLayout.setVerticalGroup(
            BHhuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel59, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        checkboxBH.setForeground(new java.awt.Color(0, 0, 0));
        checkboxBH.setLabel("Bán hàng");
        checkboxBH.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxBHItemStateChanged(evt);
            }
        });

        checkboxNH.setForeground(new java.awt.Color(0, 0, 0));
        checkboxNH.setLabel("Nhập hàng");
        checkboxNH.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxNHItemStateChanged(evt);
            }
        });

        comboBH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bán hàng" }));
        comboBH.setSelectedIndex(-1);
        comboBH.setEnabled(false);

        comboNH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhập hàng" }));
        comboNH.setSelectedIndex(-1);
        comboNH.setEnabled(false);
        comboNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNHActionPerformed(evt);
            }
        });

        checkboxSP.setForeground(new java.awt.Color(0, 0, 0));
        checkboxSP.setLabel("Sản phẩm");
        checkboxSP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxSPItemStateChanged(evt);
            }
        });

        comboSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chỉ xem", "Xem và quản lý" }));
        comboSP.setSelectedIndex(-1);
        comboSP.setEnabled(false);
        comboSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSPActionPerformed(evt);
            }
        });

        checkboxNV.setForeground(new java.awt.Color(0, 0, 0));
        checkboxNV.setLabel("Nhân viên");
        checkboxNV.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxNVItemStateChanged(evt);
            }
        });

        comboNCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chỉ xem", "Xem và quản lý" }));
        comboNCC.setSelectedIndex(-1);
        comboNCC.setEnabled(false);

        checkboxNCC.setForeground(new java.awt.Color(0, 0, 0));
        checkboxNCC.setLabel("Nhà cung cấp");
        checkboxNCC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxNCCItemStateChanged(evt);
            }
        });

        comboKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chỉ xem", "Xem và quản lý" }));
        comboKH.setSelectedIndex(-1);
        comboKH.setEnabled(false);

        checkboxKH.setForeground(new java.awt.Color(0, 0, 0));
        checkboxKH.setLabel("Khách hàng");
        checkboxKH.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxKHItemStateChanged(evt);
            }
        });

        checkboxTK.setForeground(new java.awt.Color(0, 0, 0));
        checkboxTK.setLabel("Tài khoản");
        checkboxTK.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxTKItemStateChanged(evt);
            }
        });

        comboTK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chỉ xem", "Xem và quản lý" }));
        comboTK.setSelectedIndex(-1);
        comboTK.setEnabled(false);

        comboHD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chỉ xem", "Xem và quản lý" }));
        comboHD.setSelectedIndex(-1);
        comboHD.setEnabled(false);
        comboHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboHDActionPerformed(evt);
            }
        });

        checkboxHD.setForeground(new java.awt.Color(0, 0, 0));
        checkboxHD.setLabel("Hóa đơn");
        checkboxHD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxHDItemStateChanged(evt);
            }
        });

        checkboxKM.setForeground(new java.awt.Color(0, 0, 0));
        checkboxKM.setLabel("Khuyến mãi");
        checkboxKM.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxKMItemStateChanged(evt);
            }
        });

        comboKM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chỉ xem", "Xem và quản lý" }));
        comboKM.setSelectedIndex(-1);
        comboKM.setEnabled(false);

        checkboxPN.setForeground(new java.awt.Color(0, 0, 0));
        checkboxPN.setLabel("Phiếu nhập");
        checkboxPN.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxPNItemStateChanged(evt);
            }
        });

        comboPN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chỉ xem", "Xem và quản lý" }));
        comboPN.setSelectedIndex(-1);
        comboPN.setEnabled(false);

        comboNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chỉ xem", "Xem và quản lý" }));
        comboNV.setSelectedIndex(-1);
        comboNV.setEnabled(false);

        checkboxQuyen.setForeground(new java.awt.Color(0, 0, 0));
        checkboxQuyen.setLabel("Quyền");
        checkboxQuyen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxQuyenItemStateChanged(evt);
            }
        });

        comboQuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chỉ xem", "Xem và quản lý" }));
        comboQuyen.setSelectedIndex(-1);
        comboQuyen.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkboxNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(comboBH, 0, 96, Short.MAX_VALUE)
                    .addComponent(comboNV, 0, 0, Short.MAX_VALUE)
                    .addComponent(comboNCC, 0, 96, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkboxNH, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxHD, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxTK, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboNH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboKH, 0, 0, Short.MAX_VALUE)
                    .addComponent(comboHD, 0, 0, Short.MAX_VALUE)
                    .addComponent(comboTK, 0, 0, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(checkboxSP, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(comboSP, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkboxKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkboxPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkboxQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboPN, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboKM, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(checkboxBH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboSP, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkboxSP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(checkboxNV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(comboKM)
                                            .addComponent(checkboxKM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(comboPN)
                                            .addComponent(checkboxPN, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(comboNV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboNH)
                            .addComponent(checkboxNH, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboHD)
                            .addComponent(checkboxHD, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboKH)
                            .addComponent(checkboxKH, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboNCC)
                            .addComponent(checkboxNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboTK)
                            .addComponent(checkboxTK, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(comboQuyen)
                        .addComponent(checkboxQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BHthem, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BHhuy, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BHthem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BHhuy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(90, 90, 90)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txTenQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTenQuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTenQuyenActionPerformed

    private void BHthemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BHthemMousePressed
        changecolor(BHthem,new Color(0,163,163));
    }//GEN-LAST:event_BHthemMousePressed

    private void BHthemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BHthemMouseReleased
        changecolor(BHthem,new Color(0,204,204));

        ThemSuaQuyenForm.btnThemMouseClicked();
        deleteTable(QuyenTable);
        QuanLyQuyenBUS qlquyenBUS = new QuanLyQuyenBUS();
        HienThiQuyen.AddTable(qlquyenBUS.getDsq(), QuyenTable);

        //        setTableCellAlignment(JLabel.CENTER,pTable);
    }//GEN-LAST:event_BHthemMouseReleased

    private void BHhuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BHhuyMouseClicked

    }//GEN-LAST:event_BHhuyMouseClicked

    private void BHhuyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BHhuyMousePressed
        changecolor(BHhuy,new Color(221,0,0));
    }//GEN-LAST:event_BHhuyMousePressed

    private void BHhuyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BHhuyMouseReleased
        changecolor(BHhuy,new Color(255,0,0));
        this.dispose();
    }//GEN-LAST:event_BHhuyMouseReleased

    private void checkboxBHItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxBHItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            comboBH.setEnabled(true);
        }else if(evt.getStateChange()==ItemEvent.DESELECTED){
            comboBH.setSelectedIndex(-1);
            comboBH.setEnabled(false);
        }
    }//GEN-LAST:event_checkboxBHItemStateChanged

    private void checkboxNHItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxNHItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            comboNH.setEnabled(true);
        }else if(evt.getStateChange()==ItemEvent.DESELECTED){
            comboNH.setSelectedIndex(-1);
            comboNH.setEnabled(false);
        }
    }//GEN-LAST:event_checkboxNHItemStateChanged

    private void comboNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboNHActionPerformed

    private void checkboxSPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxSPItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            comboSP.setEnabled(true);
        }else if(evt.getStateChange()==ItemEvent.DESELECTED){
            comboSP.setSelectedIndex(-1);
            comboSP.setEnabled(false);
        }
    }//GEN-LAST:event_checkboxSPItemStateChanged

    private void comboSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSPActionPerformed

    private void checkboxNVItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxNVItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            comboNV.setEnabled(true);
        }else if(evt.getStateChange()==ItemEvent.DESELECTED){
            comboNV.setSelectedIndex(-1);
            comboNV.setEnabled(false);
        }
    }//GEN-LAST:event_checkboxNVItemStateChanged

    private void checkboxNCCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxNCCItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            comboNCC.setEnabled(true);
        }else if(evt.getStateChange()==ItemEvent.DESELECTED){
            comboNCC.setSelectedIndex(-1);
            comboNCC.setEnabled(false);
        }
    }//GEN-LAST:event_checkboxNCCItemStateChanged

    private void checkboxKHItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxKHItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            comboKH.setEnabled(true);
        }else if(evt.getStateChange()==ItemEvent.DESELECTED){
            comboKH.setSelectedIndex(-1);
            comboKH.setEnabled(false);
        }
    }//GEN-LAST:event_checkboxKHItemStateChanged

    private void checkboxTKItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxTKItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            comboTK.setEnabled(true);
        }else if(evt.getStateChange()==ItemEvent.DESELECTED){
            comboTK.setSelectedIndex(-1);
            comboTK.setEnabled(false);
        }
    }//GEN-LAST:event_checkboxTKItemStateChanged

    private void comboHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboHDActionPerformed

    private void checkboxHDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxHDItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            comboHD.setEnabled(true);
        }else if(evt.getStateChange()==ItemEvent.DESELECTED){
            comboHD.setSelectedIndex(-1);
            comboHD.setEnabled(false);
        }
    }//GEN-LAST:event_checkboxHDItemStateChanged

    private void checkboxKMItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxKMItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            comboKM.setEnabled(true);
        }else if(evt.getStateChange()==ItemEvent.DESELECTED){
            comboKM.setSelectedIndex(-1);
            comboKM.setEnabled(false);
        }
    }//GEN-LAST:event_checkboxKMItemStateChanged

    private void checkboxPNItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxPNItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            comboPN.setEnabled(true);
        }else if(evt.getStateChange()==ItemEvent.DESELECTED){
            comboPN.setSelectedIndex(-1);
            comboPN.setEnabled(false);
        }
    }//GEN-LAST:event_checkboxPNItemStateChanged

    private void checkboxQuyenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxQuyenItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            comboQuyen.setEnabled(true);
        }else if(evt.getStateChange()==ItemEvent.DESELECTED){
            comboQuyen.setSelectedIndex(-1);
            comboQuyen.setEnabled(false);
        }
    }//GEN-LAST:event_checkboxQuyenItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addQuyen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BHhuy;
    private javax.swing.JPanel BHthem;
    private static java.awt.Checkbox checkboxBH;
    private static java.awt.Checkbox checkboxHD;
    private static java.awt.Checkbox checkboxKH;
    private static java.awt.Checkbox checkboxKM;
    private static java.awt.Checkbox checkboxNCC;
    private static java.awt.Checkbox checkboxNH;
    private static java.awt.Checkbox checkboxNV;
    private static java.awt.Checkbox checkboxPN;
    private static java.awt.Checkbox checkboxQuyen;
    private static java.awt.Checkbox checkboxSP;
    private static java.awt.Checkbox checkboxTK;
    private static javax.swing.JComboBox<String> comboBH;
    private static javax.swing.JComboBox<String> comboHD;
    private static javax.swing.JComboBox<String> comboKH;
    private static javax.swing.JComboBox<String> comboKM;
    private static javax.swing.JComboBox<String> comboNCC;
    private static javax.swing.JComboBox<String> comboNH;
    private static javax.swing.JComboBox<String> comboNV;
    private static javax.swing.JComboBox<String> comboPN;
    private static javax.swing.JComboBox<String> comboQuyen;
    private static javax.swing.JComboBox<String> comboSP;
    private static javax.swing.JComboBox<String> comboTK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    public static javax.swing.JTextField txMaQuyen;
    public static javax.swing.JTextField txTenQuyen;
    // End of variables declaration//GEN-END:variables
}
